---
title: "projet_stat"
output:
  word_document: default
date: "2023-01-18"
---

```{r, echo=FALSE}
setwd("~/Documents/3A/Stats/projet") #mettre votre directory
```


## Librairies
```{r setup, include=FALSE}
library(corrplot)
library(FactoMineR)
library(factoextra)
library(glmnet)
```

## Dataframe

```{r}
load('nutrimouse.rda')
```

## Pre-processing

```{r}
data_gene = nutrimouse[['gene']]
data_lipid = nutrimouse[['lipid']]
diet = nutrimouse[['diet']]
genotype = nutrimouse[['genotype']]
data_both = cbind(data_gene, data_lipid)
data_both_gen = cbind(diet, data_both)
data = cbind(genotype, data_both_gen)
rm(data_gene, data_lipid, diet, genotype, data_both, data_both_gen, nutrimouse)
```

```{r}
summary(data)
```

## Matrices de corrélation sur l'ensemble des individus

```{r}
data_gen <- data[, 1:122]
corrplot(cor(data_gen[, 3:122]))
```

```{r}
data_lipid <- cbind(data[,1:2], data[, 123:143])
corrplot(cor(data_lipid[, 3:23]))
```

## Matrices de corrélation sur chaque groupe de souris (wt ou ppar)

```{r}
data_lipid_wt <- cbind(data[, 1:2], data[1:20, 123:143])
corrplot(cor(data_lipid_wt[,3:23]))
```

```{r}
data_lipid_ppar <- cbind(data[,1:2], data[21:40, 123:143])
corrplot(cor(data_lipid_ppar[3:23]))
```

## PCA

```{r}
res.pca <- PCA(data_gen[,3:122], graph = FALSE) #TRUE affiche 2 graphes directement
get_eigenvalue(res.pca) #donne un tableau avec les valeurs propres
fviz_pca_var(res.pca, axes=1:2)
data_gen$genotype <- as.factor(data_gen$genotype)
colors <- c("red", "blue")
fviz_pca_ind(res.pca, axes = 1:2, geom = "point",
             habillage = data_gen$genotype,
             col.hab = colors,
             ggtheme = theme_classic(),
             legend = "bottom")
fviz_eig(res.pca, addlabels = TRUE, ylim = c(0,50)) #graphe avec inertie
```

```{r}

```

